### ISSUE TITLE
Elastix wrapper reopens a signed image format

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/ijl-utilities-wrappers#1]
When using the Transform Image plugin after a registration is done, the newly opened image is a signed 16 bit image, which is handled badly by ImageJ.

Potential solution:
* Try in Elastix parameter to set the output as "unsigned short", but for an unknown reason, elastix fails to write the output image, at least in ubuntu
* Export all in float...
* Use MHD file format, look at @tischi code
* dirty : substract 32768 to the rea image
* use dataset io service and check whether it can handle signed int

**Comment by tischi** [comment]
using mhd works well for me...
i have all the code, if you need.

**Comment by NicoKiaru** [comment]
For the moment I solved it by always returning float images...
