### ISSUE TITLE
Cellpose wrapper not working when Diameter Threshold set in the GUI to value different from default

### ISSUE THREAD

**Issue by giocard** [BIOP/ijl-utilities-wrappers#17]
The argument _--diam_threshold_ is added to the cellpose command line when the corresponding parameter _Diameter Threshold_ in the GUI is modfied, but the argument is not recognized by cellpose because it is not in the list of accepted arguments.
The error returned is 
`__main__.py: error: unrecognized arguments: --diam_threshold
`

**Comment by NicoKiaru** [comment]
Thanks, @romainGuiet is not here this week. I think he will have a look next week.

**Comment by giocard** [comment]
Hi @romainGuiet ,

I am using cellpose 2.0.5
If the value in the GUI is 12, then it is considered the default and no specific argument is appended to the command line.
If the value is different than 12, then the argument --diam_threshold is appended, and cellpose complains because it does not recognize it.

**Comment by romainGuiet** [comment]
Hi @giocard ,

indeed in version 2.x.x , the` --diam_threshold` is no longer available (see [rtd ](https://cellpose.readthedocs.io/en/latest/command.html?highlight=Command%20line%20examples) or use `cellpose -h` from your conda env).

I will add another exception in the plugin code to handle it, but so far the quick fix is to leave at 12 or install a cellpose 1.x.x

Cheers,

R
