### ISSUE TITLE
no access to cellpose 

### ISSUE THREAD

**Issue by Erwan67** [BIOP/ijl-utilities-wrappers#21]
Hello,

I would like to use fiji/cellpose with my laptop. I have upgraded my fiji with update function : IBMP-CNRS 
ImageScience and PTBIOP - and I have created the BIOP-Dev https://biop.epfl.ch/Fiji-Update-Dev/.
and I haven't cellpose in BIOP plugin...
![image](https://user-images.githubusercontent.com/51329059/186923474-a1f28238-52af-4f78-8a32-4e0dedd54cbc.png)

do you have some idea?
thank you

**Comment by lacan** [comment]
Hi
If you type "cellpose" in the search bar, does it find it? 
Could it be for some reason all the waz to the bottom of the plugins menu? Sometimes when it's an ImageJ2 command, it can end up at the bottom

**Comment by Erwan67** [comment]
Hi 
if i type cellpose in seach bar, there is no result....

**Comment by lacan** [comment]
This has been fixed becuase it sems our old PTBIOP-DEV update site had an out of date version of our Wrappers Library
