### ISSUE TITLE
Label image default to colorful LUT (glasbey) and create ROIs

### ISSUE THREAD

**Issue by romainGuiet** [BIOP/ijl-utilities-wrappers#40]
Suggested in this [post](https://forum.image.sc/t/fiji-wrapper-s-for-cellpose-and-omnipose-new-version-big-decisions/94735/8?u=romainguiet)

**Comment by NicoKiaru** [comment]
Duplicate see https://github.com/BIOP/ijl-utilities-wrappers/issues/44
