### ISSUE TITLE
macOs cellpose wrapper

### ISSUE THREAD

**Issue by mutterer** [BIOP/ijl-utilities-wrappers#9]
Hi, 
I see that Linux and MacOs are not supported by the cellpose wrapper. Is there a particular blocker for this?
After installing cellpose on osx following the default procedure, I can run it from the command line like this:

conda activate cellpose ; python -m cellpose --dir /Users/jmutterer/Downloads/images/pollen --pretrained_model nuclei --diameter 0. --save_png

Thanks!

**Comment by romainGuiet** [comment]
Version 0.7.0 works on MacOS 🎉

**Comment by mutterer** [comment]
Great news thanks!
